### ISSUE TITLE
能不能取消用户第一次向我发消息时的推广，或者把字数控制在10个字左右，并取消链接预览

### ISSUE THREAD

**Issue by bian2022** [LloydAsp/nfd#1]

**Comment by LloydAsp** [comment]
程序已更新，可以设置const enable_notification = false取消这个通知。

**Comment by bian2022** [comment]
> 程序已更新，可以设置const enable_notification = false取消这个通知。

谢谢

**Comment by bian2022** [comment]
> 程序已更新，可以设置const enable_notification = false取消这个通知。

是js脚本中第11行那个吗？
我把true改成false了，但还是有
