### ISSUE TITLE
无法保存代码部署

### ISSUE THREAD

**Issue by arlettebrook** [LloydAsp/nfd#15]
复制代码之后，保存部署报错：API Request Failed: PUT /api/v4/accounts/6f8d5dcd5992cba465ab9be6re08/workers/services/forward-tg-msg/environments/production?include_subdomain_availability=true (403)
有大佬知道如何解决吗？

**Comment by wuxiaosu** [comment]
试试把这几行
```js
    if(/^\/block$/.exec(message.text)){
      return handleBlock(message)
    }
    if(/^\/unblock$/.exec(message.text)){
      return handleUnBlock(message)
    }
    if(/^\/checkblock$/.exec(message.text)){
      return checkBlock(message)
    }
```
改成这样
```js
    if (message.text === '/block') {
      return handleBlock(message);
    }
    if (message.text === '/unblock') {
      return handleUnBlock(message);
    }
    if (message.text === '/checkblock') {
      return checkBlock(message);
    }
```

**Comment by arlettebrook** [comment]
> 试试把这几行
> 
> ```js
>     if(/^\/block$/.exec(message.text)){
>       return handleBlock(message)
>     }
>     if(/^\/unblock$/.exec(message.text)){
>       return handleUnBlock(message)
>     }
>     if(/^\/checkblock$/.exec(message.text)){
>       return checkBlock(message)
>     }
> ```
> 
> 改成这样
> 
> ```js
>     if (message.text === '/block') {
>       return handleBlock(message);
>     }
>     if (message.text === '/unblock') {
>       return handleUnBlock(message);
>     }
>     if (message.text === '/checkblock') {
>       return checkBlock(message);
>     }
> ```

**感谢大佬，成功解决！**
