### ISSUE TITLE
第一次使用会自动回复项目链接

### ISSUE THREAD

**Issue by iislong** [LloydAsp/nfd#6]
https://github.com/LloydAsp/nfd/issues/1 
这个问题还存在

**Comment by abiglee** [comment]
第9行
const startMsgUrl = 'https://raw.githubusercontent.com/LloydAsp/nfd/main/data/startMessage.md';

> Bot Created Via [NFD](https://github.com/LloydAsp/nfd)
> 
> 使用方法：
> 
> - 当其他用户给bot发消息，会被转发到bot创建者
> - 用户回复普通文字给转发的消息时，会回复到原消息发送者
> - 用户回复 `/block` ,  `/unblock` ,  `/checkblock` 等命令会执行相关指令， **不会** 回复到原消息发送者

自己改一下呗

**Comment by iislong** [comment]
谢谢，已解决

**Comment by iislong** [comment]
谢谢，已解决
